<?php
/**
 * @file
 * openacademy_courses_democontent.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function openacademy_courses_democontent_content_defaults() {
  $content = array();

  $content['openacademy-courses-defaultcontent-1'] = (object) array(
    'exported_path' => 'courses/welsh-onion-chickweed-brinjal',
    'title' => 'Welsh onion chickweed brinjal',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330909620',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-1',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Plectranthus collard greens soko, bitterleaf chickweed, chrysanthemum leaves bok choy bell pepper. Bitter melon brussels sprout horseradish mizuna greens gobo cabbage fava bean cardoon pea sprouts salsify burdock. Tomatillo zucchini winged bean turnip greens sierra leone bologi? Horse gram chard sweet potato or kumara - radish asparagus runner bean. Daikon, fiddlehead arugula peanut polk brinjal?</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Plectranthus collard greens soko, bitterleaf chickweed, chrysanthemum leaves bok choy bell pepper. Bitter melon brussels sprout horseradish mizuna greens gobo cabbage fava bean cardoon pea sprouts salsify burdock. Tomatillo zucchini winged bean turnip greens sierra leone bologi? Horse gram chard sweet potato or kumara - radish asparagus runner bean. Daikon, fiddlehead arugula peanut polk brinjal?</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '14',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 105',
          'format' => NULL,
          'safe_value' => 'OA 105',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '4',
          'format' => NULL,
          'safe_value' => '4',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Fava bean, tatsoi tinda ginger, dandelion ti lettuce celery swiss chard.',
          'format' => NULL,
          'safe_value' => 'Fava bean, tatsoi tinda ginger, dandelion ti lettuce celery swiss chard.',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '2',
          'starthours' => '1400',
          'endhours' => '1600',
        ),
        1 => array(
          'day' => '6',
          'starthours' => '1400',
          'endhours' => '1600',
        ),
        2 => array(
          'day' => '10',
          'starthours' => '1400',
          'endhours' => '1600',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '8',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '11',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-10'] = (object) array(
    'exported_path' => 'courses/moth-bean-leek',
    'title' => 'Moth bean leek',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910400',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-10',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Lamb\'s lettuce, dandelion horseradish moth bean, scallion celery; pea burdock soybean. Rutabaga collard greens arracacha ginger pak choy fat hen arracacha. Broccoli Rabe - hamburg parsley lagos bologi - green bean, garbanzo. Taro cassava turnip greens. Yam - pak choy ulluco cress burdock cauliflower tarwi. Ahipa tomatillo horseradish bok choy, asparagus swede prussian asparagus. Bitter gourd camas, leek common bean.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Lamb\'s lettuce, dandelion horseradish moth bean, scallion celery; pea burdock soybean. Rutabaga collard greens arracacha ginger pak choy fat hen arracacha. Broccoli Rabe - hamburg parsley lagos bologi - green bean, garbanzo. Taro cassava turnip greens. Yam - pak choy ulluco cress burdock cauliflower tarwi. Ahipa tomatillo horseradish bok choy, asparagus swede prussian asparagus. Bitter gourd camas, leek common bean.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '5',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 499',
          'format' => NULL,
          'safe_value' => 'OA 499',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Endive canna, collard greens water spinach prussian asparagus pigeon pea pignut salsify leaves radicchio.',
          'format' => NULL,
          'safe_value' => 'Endive canna, collard greens water spinach prussian asparagus pigeon pea pignut salsify leaves radicchio.',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '6',
          'starthours' => '900',
          'endhours' => '1300',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '11',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-2'] = (object) array(
    'exported_path' => 'courses/polk-tomato-arugula',
    'title' => 'Polk tomato arugula',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330909800',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-2',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Chard good king henry. Lagos bologi, winged bean golden samphire ginger chickweed, tomato brinjal, carrot aubergine. Mung bean fiddlehead avocado brussels sprout ceylon spinach runner bean epazote paracress. Winged bean celery swiss chard bamboo shoot ginger tigernut - lima bean. Winged bean epazote, winged bean good king henry, chickweed chaya. Horseradish orache golden samphire ceylon spinach samphire daikon brinjal leaves broadleaf arrowhead ahipa black-eyed pea yam, taro. Kuka kurrat asparagus scorzonera rutabaga tigernut courgette pak choy indian pea.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Chard good king henry. Lagos bologi, winged bean golden samphire ginger chickweed, tomato brinjal, carrot aubergine. Mung bean fiddlehead avocado brussels sprout ceylon spinach runner bean epazote paracress. Winged bean celery swiss chard bamboo shoot ginger tigernut - lima bean. Winged bean epazote, winged bean good king henry, chickweed chaya. Horseradish orache golden samphire ceylon spinach samphire daikon brinjal leaves broadleaf arrowhead ahipa black-eyed pea yam, taro. Kuka kurrat asparagus scorzonera rutabaga tigernut courgette pak choy indian pea.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '1',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 150',
          'format' => NULL,
          'safe_value' => 'OA 150',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Chard good king henry. Lagos bologi, winged bean golden samphire ginger chickweed, tomato brinjal, carrot aubergine',
          'format' => NULL,
          'safe_value' => 'Chard good king henry. Lagos bologi, winged bean golden samphire ginger chickweed, tomato brinjal, carrot aubergine',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '4',
          'starthours' => '1300',
          'endhours' => '1600',
        ),
        1 => array(
          'day' => '8',
          'starthours' => '1300',
          'endhours' => '1600',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '12',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-3'] = (object) array(
    'exported_path' => 'courses/indian-pea-green-bean',
    'title' => 'Indian pea, green bean',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910160',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-3',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Cardoon dandelion parsnip chrysanthemum leaves bitter gourd. Skirret winged bean, tepary bean; lotus root; runner bean, leaves kale bok choy radicchio guar plectranthus. Napa cabbage - tatsoi burdock tigernut leek, canna chrysanthemum leaves tepary bean lettuce. Mung bean - tomato sweet pepper pea sprouts kale lagos bologi kuka. Fluted pumpkin spring onion black-eyed pea sea beet.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Cardoon dandelion parsnip chrysanthemum leaves bitter gourd. Skirret winged bean, tepary bean; lotus root; runner bean, leaves kale bok choy radicchio guar plectranthus. Napa cabbage - tatsoi burdock tigernut leek, canna chrysanthemum leaves tepary bean lettuce. Mung bean - tomato sweet pepper pea sprouts kale lagos bologi kuka. Fluted pumpkin spring onion black-eyed pea sea beet.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '13',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 211',
          'format' => NULL,
          'safe_value' => 'OA 211',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Ensete plectranthus lamb\'s lettuce, gumbo summer purslane bitterleaf, radish.',
          'format' => NULL,
          'safe_value' => 'Ensete plectranthus lamb&#039;s lettuce, gumbo summer purslane bitterleaf, radish.',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '6',
          'starthours' => '1700',
          'endhours' => '2200',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '11',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-4'] = (object) array(
    'exported_path' => 'courses/fava-bean-catsear',
    'title' => 'Fava bean catsear',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910160',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-4',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Tomato onion garbanzo yacón. Lamb\'s lettuce pak choy, beetroot catsear runner bean asparagus peanut.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Tomato onion garbanzo yacón. Lamb\'s lettuce pak choy, beetroot catsear runner bean asparagus peanut.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '6',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 255',
          'format' => NULL,
          'safe_value' => 'OA 255',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Garden Rocket bitter melon taro melokhia kuka',
          'format' => NULL,
          'safe_value' => 'Garden Rocket bitter melon taro melokhia kuka',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '2',
          'starthours' => '1500',
          'endhours' => '1700',
        ),
        1 => array(
          'day' => '6',
          'starthours' => '1500',
          'endhours' => '1700',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '12',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-5'] = (object) array(
    'exported_path' => 'courses/horseradish-samphire',
    'title' => 'Horseradish samphire',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910220',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-5',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Arracacha turnip greens carrot kuka elephant garlic; ricebean tomato! Moth bean okra pigeon pea golden samphire dolichos bean kai-lan elephant foot yam squash. American groundnut pumpkin fava bean lettuce pea corn salad manioc bamboo shoot kai-lan. Soko. Radish sorrel, courgette sea beet land cress bell pepper.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Arracacha turnip greens carrot kuka elephant garlic; ricebean tomato! Moth bean okra pigeon pea golden samphire dolichos bean kai-lan elephant foot yam squash. American groundnut pumpkin fava bean lettuce pea corn salad manioc bamboo shoot kai-lan. Soko. Radish sorrel, courgette sea beet land cress bell pepper.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '13',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 310',
          'format' => NULL,
          'safe_value' => 'OA 310',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3Moth bean spinach mung bean tarwi, carrot rutabaga',
          'format' => NULL,
          'safe_value' => '3Moth bean spinach mung bean tarwi, carrot rutabaga',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Moth bean spinach mung bean tarwi, carrot rutabaga',
          'format' => NULL,
          'safe_value' => 'Moth bean spinach mung bean tarwi, carrot rutabaga',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '4',
          'starthours' => '2100',
          'endhours' => '2330',
        ),
        1 => array(
          'day' => '8',
          'starthours' => '2100',
          'endhours' => '2330',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '11',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-6'] = (object) array(
    'exported_path' => 'courses/prussian-asparagus',
    'title' => 'Prussian asparagus',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910220',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-6',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Turnip greens; catsear sweet potato or kumara potato, cucumber. Summer purslane brussels sprout squash, asparagus yacón chickweed. Cardoon turnip greens spring onion pea sprouts pumpkin swiss chard chickweed; bell pepper tatsoi chickweed. Napa cabbage peanut urad bean.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Turnip greens; catsear sweet potato or kumara potato, cucumber. Summer purslane brussels sprout squash, asparagus yacón chickweed. Cardoon turnip greens spring onion pea sprouts pumpkin swiss chard chickweed; bell pepper tatsoi chickweed. Napa cabbage peanut urad bean.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '23',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 350',
          'format' => NULL,
          'safe_value' => 'OA 350',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Polk fiddlehead tarwi sweet pepper',
          'format' => NULL,
          'safe_value' => 'Polk fiddlehead tarwi sweet pepper',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '4',
          'starthours' => '1400',
          'endhours' => '1800',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '11',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-7'] = (object) array(
    'exported_path' => 'courses/broadleaf-arrowhead-bitter-melon',
    'title' => 'Broadleaf arrowhead bitter melon ',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910280',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-7',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<div><p>Land cress fluted pumpkin leek fluted pumpkin. Ricebean lizard\'s tail scallion epazote rutabaga bitter melon. Tinda - chinese artichoke. Lotus root ti ceylon spinach runner bean radish lentil pumpkin scorzonera guar orache prairie turnip prairie turnip. Common bean sweet potato or kumara hamburg parsley tepary bean bitter melon arugula scorzonera land cress asparagus; daikon carrot? Sea kale, indian pea bitter gourd cardoon beet greens cardoon onion soybean; ahipa, summer purslane. Ricebean bamboo shoot; cardoon ulluco, new zealand spinach bitterleaf.</p><div></div></div>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<div>
  <p>Land cress fluted pumpkin leek fluted pumpkin. Ricebean lizard\'s tail scallion epazote rutabaga bitter melon. Tinda - chinese artichoke. Lotus root ti ceylon spinach runner bean radish lentil pumpkin scorzonera guar orache prairie turnip prairie turnip. Common bean sweet potato or kumara hamburg parsley tepary bean bitter melon arugula scorzonera land cress asparagus; daikon carrot? Sea kale, indian pea bitter gourd cardoon beet greens cardoon onion soybean; ahipa, summer purslane. Ricebean bamboo shoot; cardoon ulluco, new zealand spinach bitterleaf.</p>
  <div></div>
  </div>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '14',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 450',
          'format' => NULL,
          'safe_value' => 'OA 450',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Manioc cauliflower, chickweed fat hen, hamburg parsley golden samphire water spinach elephant foot yam, horseradish.',
          'format' => NULL,
          'safe_value' => 'Manioc cauliflower, chickweed fat hen, hamburg parsley golden samphire water spinach elephant foot yam, horseradish.',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '2',
          'starthours' => '800',
          'endhours' => '930',
        ),
        1 => array(
          'day' => '6',
          'starthours' => '800',
          'endhours' => '930',
        ),
        2 => array(
          'day' => '10',
          'starthours' => '800',
          'endhours' => '930',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '12',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-8'] = (object) array(
    'exported_path' => 'courses/sea-beet-chickweed',
    'title' => 'Sea beet chickweed',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910340',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-8',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Runner bean endive canna polk moth bean chinese mallow; chickweed, komatsuna water spinach common bean tomato tigernut. Napa cabbage spring onion dolichos bean bok choy winter purslane cucumber azuki bean arracacha okra runner bean epazote yam. Tinda, chickweed ceylon spinach, watercress sea kale. Scallion ensete arugula sea beet watercress. New Zealand Spinach miner\'s lettuce, chinese cabbage water chestnut guar. Tarwi new zealand spinach earthnut pea dandelion leaves tomato.</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Runner bean endive canna polk moth bean chinese mallow; chickweed, komatsuna water spinach common bean tomato tigernut. Napa cabbage spring onion dolichos bean bok choy winter purslane cucumber azuki bean arracacha okra runner bean epazote yam. Tinda, chickweed ceylon spinach, watercress sea kale. Scallion ensete arugula sea beet watercress. New Zealand Spinach miner\'s lettuce, chinese cabbage water chestnut guar. Tarwi new zealand spinach earthnut pea dandelion leaves tomato.</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '7',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 451',
          'format' => NULL,
          'safe_value' => 'OA 451',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '3',
          'format' => NULL,
          'safe_value' => '3',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Pea sprouts mizuna greens kale eggplant radicchio, broccoli rabe, gobo sweet potato or kumara, gumbo, fiddlehead sierra leone bologi soko',
          'format' => NULL,
          'safe_value' => 'Pea sprouts mizuna greens kale eggplant radicchio, broccoli rabe, gobo sweet potato or kumara, gumbo, fiddlehead sierra leone bologi soko',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '4',
          'starthours' => '1000',
          'endhours' => '1200',
        ),
        1 => array(
          'day' => '8',
          'starthours' => '1000',
          'endhours' => '1200',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '12',
        ),
      ),
    ),
  );

  $content['openacademy-courses-defaultcontent-9'] = (object) array(
    'exported_path' => 'courses/scallion-yarrow-elephant',
    'title' => 'Scallion yarrow elephant',
    'status' => '1',
    'promote' => '1',
    'sticky' => '0',
    'type' => 'openacademy_course',
    'language' => 'und',
    'created' => '1330910340',
    'comment' => '0',
    'translate' => '0',
    'machine_name' => 'openacademy-courses-defaultcontent-9',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Indian pea broadleaf arrowhead orache, orache tinda summer purslane turnip greens arugula. Carrot, swiss chard yardlong bean pumpkin napa cabbage napa cabbage canna. Horseradish earthnut pea, kurrat. Lentil celeriac american groundnut mooli ensete summer purslane. Runner bean cress, napa cabbage, turnip greens tomatillo canna broccoli rabe chinese mallow tatsoi! Parsnip lagos bologi; pigeon pea tomatillo, soybean pigeon pea canna golden samphire melokhia soko?</p>',
          'summary' => '',
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '<p>Indian pea broadleaf arrowhead orache, orache tinda summer purslane turnip greens arugula. Carrot, swiss chard yardlong bean pumpkin napa cabbage napa cabbage canna. Horseradish earthnut pea, kurrat. Lentil celeriac american groundnut mooli ensete summer purslane. Runner bean cress, napa cabbage, turnip greens tomatillo canna broccoli rabe chinese mallow tatsoi! Parsnip lagos bologi; pigeon pea tomatillo, soybean pigeon pea canna golden samphire melokhia soko?</p>
  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_course_people' => array(
      'und' => array(
        0 => array(
          'target_id' => '2',
        ),
      ),
    ),
    'field_course_number' => array(
      'und' => array(
        0 => array(
          'value' => 'OA 475',
          'format' => NULL,
          'safe_value' => 'OA 475',
        ),
      ),
    ),
    'field_course_credits' => array(
      'und' => array(
        0 => array(
          'value' => '5',
          'format' => NULL,
          'safe_value' => '5',
        ),
      ),
    ),
    'field_course_location' => array(
      'und' => array(
        0 => array(
          'value' => 'Orache pak choy mizuna greens melokhia, golden samphire wild leek chickpea samphire. ',
          'format' => NULL,
          'safe_value' => 'Orache pak choy mizuna greens melokhia, golden samphire wild leek chickpea samphire. ',
        ),
      ),
    ),
    'field_course_time' => array(
      'und' => array(
        0 => array(
          'day' => '2',
          'starthours' => '800',
          'endhours' => '1130',
        ),
        1 => array(
          'day' => '10',
          'starthours' => '800',
          'endhours' => '1130',
        ),
      ),
    ),
    'field_course_type' => array(
      'und' => array(
        0 => array(
          'tid' => '7',
        ),
      ),
    ),
    'field_course_term' => array(
      'und' => array(
        0 => array(
          'tid' => '11',
        ),
      ),
    ),
  );

return $content;
}
