<?php
/**
 * @file
 * Code for the Open Academy Courses feature.
 */

include_once('openacademy_courses.features.inc');


/**
 * Implements hook_panelizer_default_types_alter()
 */
function openacademy_courses_panelizer_defaults_alter(&$defaults) {
  // Require the panels panelizer include from features since 
  // features doesn't support hook_panelizer_defaults() correctly.
  // See https://drupal.org/node/1427150 for more on that.
  require_once('openacademy_courses.panelizer.inc');
  foreach(openacademy_courses_panelizer_defaults() as $name => $default) {
    $defaults[$name] = $default;
  }
}

/**
 * Implementation of hook_apps_app_info()
 */
function openacademy_courses_apps_app_info() {
  return array(
    // 'demo content description' => 'This tells what add demo content will do it is placed on the configure form',
    'demo content module' => 'openacademy_courses_democontent',
    'configure form' => 'openacademy_courses_configure_form',
    // 'post install callback' => 'appname_app_post_install', // This will be called after the app is enabled intialy or of the app has been uninstalled
    // 'status callback' => 'appname_app_status'
  );
}

/** 
 * App Configuration Form
 */
function openacademy_courses_configure_form($form, &$form_state) {
  $form = array();

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

   return $form;
}
