<?php
/**
 * @file
 * openacademy_courses.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function openacademy_courses_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "panelizer" && $api == "panelizer") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function openacademy_courses_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("version" => "3.0");
  }
}

/**
 * Implements hook_node_info().
 */
function openacademy_courses_node_info() {
  $items = array(
    'openacademy_course' => array(
      'name' => t('Course'),
      'base' => 'node_content',
      'description' => t('An important course to post to your site.
'),
      'has_title' => '1',
      'title_label' => t('Name of Course'),
      'help' => '',
    ),
  );
  return $items;
}
